version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-movies
    container_name: api
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- /app/node_modules/.bin/nest start --watch

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:  
      - dbdata:/var/lib/postgresql/data/  
    networks:
      - app-network

  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - app-network
    ports:
      - "8081:8081"
    depends_on:
        - redis-cache

  pgadmin:
    links:
      - db:db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/root/.pgadmin
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  pgadmindata:
  node_modules:
  redis_data:
